//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orderBookingApi.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderCode { get; set; }
        public string IMEI { get; set; }
        public string PIN { get; set; }
        public string DeviceColor { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> OrderKindID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderKindsLkp OrderKindsLkp { get; set; }
        public virtual PaymentTypeLkp PaymentTypeLkp { get; set; }
        public virtual Service Service { get; set; }
    }
}
